### Songs
Get http://localhost:3000/songs
###
Get http://localhost:3000/songs/2
###
Get http://localhost:3000/songs/9999

### Artists
Get http://localhost:3000/artists
###
Get http://localhost:3000/artists/1